apiVersion: v1
kind: Namespace
metadata:
  name: fith
  labels:
    name: fith
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
  namespace: fith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
      - name: app
        image: nginxinc/nginx-unprivileged
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
  namespace: fith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
      - name: app
        image: nginxinc/nginx-unprivileged
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fe-service
  namespace: fith
spec:
  selector:
    app: fe
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: be-service
  namespace: fith
spec:
  selector:
    app: be
  ports:
  - port: 80
    targetPort: 8080
---
# Allow fe to access be
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-fe-to-be
  namespace: fith
spec:
  podSelector:
    matchLabels:
      app: be
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: fe
---
# Block be from accessing fe (deny all ingress to fe)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-be-to-fe
  namespace: fith
spec:
  podSelector:
    matchLabels:
      app: fe
  policyTypes:
  - Ingress
